Create Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
hpe-dev-incubator/hpe-dev-portal pull request #1126
Opened 2022-04-27 11:52 UTC by Didier-Lalli

Automatically generated by Netlify CMS

2022-05-02 16:08 UTC, ma-los commented on content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
> +\-      [ Learn more about the HPE GreenLake Terraform provider](https://registry.terraform.io/providers/HewlettPackard/hpegl/0.1.0-beta7)
Sounds like they moving to HPE ?! Also prefer url without version trailer.
https://registry.terraform.io/providers/HPE/hpegl

2022-05-02 16:08 UTC, ma-los commented on content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
> +Go ahead and add the following code snippet to your configuration file:
I like the way you tell to append the config file ... this could be confusing for others use cases

2022-05-03 10:53 UTC, choukden requested changes
Great blog Didier.
Easy to read and easy to walk through the different steps to manage the lifecycle of the VM with Terraform once the VM is provisioned in GreenLake.

Just a couple of comments/suggestions.

Denis

2022-05-03 10:53 UTC, choukden commented on content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
> +![DidierTest1 VM as created in Part 1](/img/terraform-greenlake-part2-blog-picture1.png "DidierTest1 VM as created in Part 1")
Didier, suggest you use this image in the first blog too. The image in the first blog is fuzzy.

2022-05-03 10:53 UTC, choukden commented on content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
> +In [my first blog post](https://developer.hpe.com/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform/), I covered how to get started with the Terraform provider for HPE GreenLake, I explain
In my first blog.....In this article, I showed you how to manage the lifecycle of the Virtual Machine using Terraform. I applied several changes to the Terraform infrastructure configuration file and observed how the desired...to HPE GreenLake.

2022-05-04 13:48 UTC, merged