Create Blog “mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service”
hpe-dev-incubator/hpe-dev-portal pull request #1334
Opened 2022-08-08 08:19 UTC by thirubeyond

Automatically generated by Netlify CMS

2022-08-09 11:00 UTC, choukden requested changes
Hi Thirukkannan

Thank you very much for your blog post contribution.

Here is a set of some suggestions for edits.
Dale Rensing will go through the editorial and grammatical review in the coming day or so.

Here are some tips to assist you with the review of the suggestions and how to acknowledge them in GitHub:

* Navigate to **File Changed** area to visualize the comments from start to the end (You may see “Load Diff” for large blog post entry, in this case just click “Load Diff”), or navigate to **Conversation** area to visualize the comments per reviewer.
* You can mark the suggestion you have incorporated in the blog post entry in the CMS Workflow Editor by clicking on button **Resolve Conversation**.

Note we recommend you to continue doing edits of the blog post entry in the CMS Workflow editor while the entry is in the **In Review** column. Moving it back to the **Drafts** column will close the Pull Request (PR) in Github and when moving the entry to the **In Review** column again a new PR in Github is created, and we will lose the suggestions for edits.

Stay tuned for additional editorial suggestions for edits from Dale.

Best regards,
Denis

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +<!--\\[if !supportLists]-->2)   <!--\\[endif]-->Place the model in s3 object storage
Please delete the special characters (\<!-- ....--\>). Copy/paste effect.

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +name: "braintumor_onnx"
suggest you embed the configuration file into a code block snippet.
use the command below:

\```markdown 
your configuration file 
\```

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +<!--\\[if !supportLists]-->3)   <!--\\[endif]-->Create a namespace and secret to place an object storage credentials
delete the special characters (\<!-- ....--\>) -  copy/paste side effect.

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Run command “kubectl create namespace triton”
suggest to make code blog snippet for the kubectl commands.
For example, you can say:
Run commands below:
\```bash
kubectl create namespace triton
kubectl create secret generic ....
\```

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +<!--\\[if !supportLists]-->4)   <!--\\[endif]-->Create a deployment to host the model and check pods and services are running
please remove special characters throughout the post.

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +
Make the YAML manifest file below a code snippet with language syntax "yaml"./
for example:
\```yaml
your yaml file here
\```

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +
enclose the two kubectl commands below in a code snippet with syntax language "bash". 
Remove the special character "\\"

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Service labels hpecp.hpe.com/hpecp-internal-gateway: "true" is placed to get a gateway endpoint to access the triton inference server outside the cluster. To find the endpoint run command “kubectl
suggest 
* Service labels ***hpecp.hpe.com/hpecp-internal-gateway: "true"*** is placed to get ....
* 
Then suggestion to enclose the kubectl command with backticks (`)

To find the endpoint run command: `kubectl describe svc <service_name> -n triton`

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +\    Inspect the external metrics endpoint using command kubectl describe svc <service_name> -n triton”
remove special character "\\" before "Inspect the external..."

Then suggestion to enclose the kubectl command with backticks (`)

 Inspect the external metrics endpoint using command: `kubectl describe svc <service_name> -n triton`

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +Triton Inference server supports deployment of any AI model from multiple deep learning and machine learning frameworks, including TensorRT, TensorFlow, PyTorch, ONNX, OpenVINO, Python, RAPIDS FIL, a
To learn more about Triton Inference server, refer to the References section at the end of the post.

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +<!--EndFragment-->
delete EndFragment sentence.

2022-08-09 11:00 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +
suggest you make the URLs hotlinks.
for example:
 * \[Triton Inference server\](https://github.com/triton-inference-server/server)

2022-08-10 08:26 UTC, choukden requested changes
Hi,

two additional comments:
please check the code snippet. Please remove the backslash within the triple backticks.

and, please keep ML Ops consistent across the post (ML Ops with a space between ML and Ops).

and finally, Ezmeral Container Platform is now known as HPE Ezmeral Runtime Enterprise.
https://www.hpe.com/us/en/software/ezmeral-runtime.html

The latest URL to the HPE Ezmeral Runtime Enterprise online doc is here:
https://docs.containerplatform.hpe.com/54/reference/HPE_Ezmeral_Container_Platform.html

Thanks
Denis

2022-08-10 08:26 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +\`\``markdown
Sorry if my previous comment was confusing. Please remove the escape character (the backslash). For a code block, you just need the triple backticks (```markdown) at the beginning of the code snippet and the triple backticks at the end of the code block. 

Make sure to specify appropriate language syntax for the first triple backticks at the beginning of the code block snippet.
Please do the same for all your code blocks  throughout the post.
Thanks,
Denis

2022-08-10 08:58 UTC, choukden commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +\`\``markdown
Yep, this looks good to me.
Thanks!!!

2022-08-12 15:55 UTC, drensing reviewed
Thank you for your patience in awaiting my review. I hope you find these suggestions helpful.

Best regards,
Dale

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +HPE GreenLake Central is an advanced software-as-a-service platform that provides you with a consistent cloud experience for all your applications and data—on-premises or off-premises. It provides yo
Hi there. The hyphens you have before and after "through the services you purchase" should have spaces between them and the words before and after them. At least, they ought to look as though they do in the final product :-).

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +HPE GreenLake for ML Ops is an on-premises, enterprise-grade ML service, enabling developers and data scientists to rapidly build, train, and deploy ML models—from pilot to production, at any scale.
Same comment with the hyphen in this sentence.

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +In this article, we focus on optimal model identified after data preparation and building model. More specifically, as an example, we shall deploy a sample ONNX model available in Kubernetes native M
It is preferred, in the HPE Developer blog posts, to not use the "Royal We". Instead, imagine yourself talking directly to the reader. That would mean, in this paragraph, you would say "In this article, I will focus on an optimal model..." (please note some additional words in there).  And the next sentence would say "More specifically, as an example, I will show you how to deploy a sample ONNX model..." (again, a couple of additional words)

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +HPE GreenLake for ML Ops platform allows customers to host their favorite cloud native applications say Mlflow, Minio, etc.
As opposed to "say", it would read better with "...native applications, like Mlflow, Minio, etc." By the way, should it be MLflow? (capital L?)

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +**Pre-requisite**
Pre-requisites (plural)

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* ML Ops project has been created by ML Ops admin and user is able to launch to HPE Ezmeral Runtime Enterprise with ML Ops Project Member Role role
Recommend changing this to:
An ML Ops project that has been created by an ML Ops admin for which the user is able to launch to HPE Ezmeral Runtime Enterprise through an ML Ops Project Member role

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Access credentials to any S3 based object storage is available
Recommend changing 33 to "Available access credentials to any S3 based object storage"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +1)   Validation connection to kubernetes cluster
Kubernetes should have an initial capital letter

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +1. Click HPE GreenLake for ML Ops card in the HPE GreenLake Central **Dashboard** shows the number of previously created projects.
Minor rewording:
Click the HPE GreenLake for ML Ops card in the HPE GreenLake Central **Dashboard**, which shows the number of previously created projects.

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +6. validate connectivity to the cluster using command “kubectl get no”
The V in validate should be a capital letter

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +1. Place the model and configuration file for triton inference server in object storage
Shouldn't Triton Inference have initial caps?

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +2. Sample configuration file for the model as is below:
Recommend changing "as is below" to "as shown below"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +3)   Create a namespace and secret for object storage credentials with below commands:
Recommend changing the last part of this sentence from "with below commands:" to "using the commands shown below:"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +4) Create a deployment to host the model and check pods and services are running
rephrase last part of sentence to "...and check that the pods and services are running"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Replace <objectstoreurl.com:port> and model path with actual object store url, model sub path where model and associate configuration is placed
This sentence isn't clear to me, but I'm not sure how to fix it, since it's not clear.

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Check the pods and service are running by running the below commands:
Recommend rephrasing to "Check that the pods and service are running using the commands shown below:"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Service labels **hpecp.hpe.com/hpecp-internal-gateway: "true"** is placed to get a gateway endpoint to access the triton inference server outside the cluster. To find the endpoint run command
"Triton Inference" initial caps?
Second sentence should have a comma and be modified to "To find the endpoint, run this command:"

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +* Check the metrics endpoints for models hosted in triton inference server are accessible:
Triton Inference?

2022-08-12 15:55 UTC, drensing commented on content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
> +Once the production model is hosted, then any application can perform inference on the model hosted by Triton inference server. More on Triton client libraries refer the references section below
Inference?
Second sentence, recommend rephrasing to "For more on Triton client libraries, refer to the section below." (add the word More, a comma and shorten sentence.)

2022-08-25 07:57 UTC, merged