Create Blog “mellanox-switch-automation-welcome-to-2012”
hpe-dev-incubator/hpe-dev-portal pull request #1427
Opened 2022-10-07 23:50 UTC by xod442

Automatically generated by Netlify CMS

2022-10-10 09:43 UTC, choukden requested changes
Hi Rick,

Thank you very much for your new contribution.
Just a couple of minor suggestions for edit to hotlink a couple of URLs.

Also, feel free to add one or more tags for your post.

Do you think your blog post could be tied to a particular "Our technologies" page here: https://developer.hpe.com/platforms ?

Dale will go through the editorial review in the coming days or so. 
Please stay tuned!

Best regards,

Denis

2022-10-10 09:43 UTC, choukden commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +A﻿ video tutorial can be found on  my personal blog here: <https://www.techworldwookie.com/automation-for-the-sake-of-automating/>
Suggest to make the URL a hotlink.

2022-10-10 09:43 UTC, choukden commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +The application runs in Docker and docker-compose needs to be installed on the host system. I just use Docker Desktop and everything becomes quite portable. The application can be found over on my gi
Suggest to make the URL a hotlink.

2022-10-10 13:57 UTC, drensing reviewed
Hi, Rick! Great to have another contribution from you. Please look through my suggestions and edits. I think you have the basis here for a really great post, but you need to hit the reader over the head right away letting them know why they want to read it.

All the best,
Dale

2022-10-10 13:57 UTC, drensing commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +I﻿ recently was involved with a proof of concept for a very large customer where these Mellanox switches would be used. The end design calls for over 200 locations.A quick calculation tells us that 4
Your first paragraph was interesting, but it didn't quite help me understand why I should read this blog post. It needs a "hook" to draw them in. In addition, there's a combination of past, present, and future tense in these paragraphs. To avoid reader confusion, it's best to stick with one tense, if possible. I understand that the project may not yet be complete but that your part may be. Consider the following rewrite of paragraphs 9, 11, and 13 to see if we can fix this:

In my recent involvement with a proof-of-concept for a very large customer who would be using Mellanox switches in over 200 locations, my job was to configure the network to support all the different connections the deployment required. I quickly calculated that 400 different switches would need to be configured. That would be a lot of typing on a terminal using the switch command line. Fortunately, I love to automate things and maintain consistency in all my switch configuration files. 

You never know when you'll run into the same issue, so let me help you out here by showing you how I handled it. First, let's take a look at the architecture:

2022-10-10 13:57 UTC, drensing commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +There are only five networks. The ILO or Out of Band management, the VMware Management network, home of vcenter, a VM production network, and two ISCSI data networks.
"ILO" should be "iLO" (lower case "i"). These two sentences, should really be one and require some changes.

"Within the architecture, there are only five networks; the iLO (or Out-of-Band management), the VMware Management network, the home of the vCenter, a VM production network, and two ISCSI data networks."

2022-10-10 13:57 UTC, drensing commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +Looking at a switch configuration file, most of the information is static. Very little of it is dynamic. There are only 17 variables that need to be collected before they can be applied to a Jinja2 t
This is the first time you bring up "Jinja2" and the template. Remember that the reader is not in front of you watching what you are doing... you'll need to explain to them somewhere before this that, in part of your automation process, you are going to be using Jinja2 and explain what that is.

2022-10-10 13:57 UTC, drensing commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +The ultimate goal is to develop the application to speak directly to the switches via the Rest API. Without having access to the hardware makes it a bit of a challenge to develop the python bindings.
The fix here may be to swap paragraphs 21 and 23 and rewrite them a little. For example:

Within the architecture, there are only five networks. The iLO (or Out-of-Band management), the VMware Management network, the home of the vCenter, a VM production network, and two ISCSI data networks.

My ultimate goal was to develop an application to speak directly to the switches via the REST API. Without having access to the hardware, it was a bit of a challenge to develop the Python bindings. Since I would be using Jinja2 templates and Flask, it required me to travel back in time to when I first learned them and remember the basic pieces I needed. 

Looking at the switch configuration file, most of the information is static. Very little of it is dynamic. There are only 17 variables that need to be collected before they can be applied to a Jinja2 template. So, the solution for me was a form.

[then, if I were you, I would **link** "Jinja2" and "Flask" to someplace on the web that gives a good explanation of what they are and where the reader can find more information on how to use them.] [Also, please note, if I am changing the meaning of anything you're saying, obviously don't take my recommendation :-). But think about how some of my suggestions may be applied to the words you need to use.]

2022-10-10 13:57 UTC, drensing commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +B﻿y changing the values in column "c", you can generate a pair of configuration files.
So, when you say "changing the values in column "C" (which should be capitalized), I do get the sense that there is a spreadsheet involved. You'll have to say more about that above to make this clearer.

2022-10-19 20:28 UTC, drensing reviewed
I may have neglected to click on "Submit review", which may have caused the issue.

Sorry!

2022-10-19 23:39 UTC, xod442 commented on content/blog/mellanox-switch-automation-welcome-to-2012.md
> +title: Mellanox switch automation welcome to 2012!
fixed

2022-10-20 08:29 UTC, merged