Create Blog “get-started-with-application-performance-monitoring-tools-overview”
hpe-dev-incubator/hpe-dev-portal pull request #1634
Opened 2023-01-03 08:24 UTC by GuopingJia

Automatically generated by Netlify CMS

2023-01-04 17:45 UTC, choukden requested changes
Hi Guoping, 
Just a couple of suggestions for edits. 

Thank you so much for such great blog post about the common APM tooling.

Dale will go through the editorial review in the coming day or so. Please stay tuned for further suggestions for edits and comments.

Thanks,

Denis

2023-01-04 17:45 UTC, choukden commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +tags:
You may want to add the tag:
hpe-greenlake-for-private-cloud-enterprise

2023-01-04 17:45 UTC, choukden commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +Elastic builds and maintains the *Elastic Stack*, an _all-in-one_ platform built upon the proven *ELK Stack* for the logs, metrics, and application trace data with a multitude of out-of-the-box integ
...upon the proven *Elasticsearch, Logstash, and Kibana (ELK) Stack* for the logs, ...

2023-01-04 17:45 UTC, choukden commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +Apache SkyWalking provides a list of agents to be used for building *Java*, *.NET Core*, *PHP*, *Node.js*, *Golang*, *LUA*, *Rust* and *C++* apps. It supports to integrate and collect data from multi
...including _Prometheus_, ....

2023-01-05 09:29 UTC, GuopingJia commented
> Hi Guoping, Just a couple of suggestions for edits.
> 
> Thank you so much for such great blog post about the common APM tooling.
> 
> Dale will go through the editorial review in the coming day or so. Please stay tuned for further suggestions for edits and comments.
> 
> Could you please confirm this post is the first of a 3 blog post series about APM tooling, and using Skywalking to monitor distributed applications and microservices deployed on K8s clusters?
> 
> Shall I assume you will submit another blog post contribution in the coming weeks to complete this 3 blog post series?
> 
> Thanks,
> 
> Denis

Thanks Denis for your review and comments. 

The new patch has been submitted that includes all your comments. 

Yes, there will be a 3 blog post series about APM tooling and using Apache SkyWalking. 2 blogs have been submitted for your review, #1634 (this blog) and #1636 (for monitoring applications deployed on K8s cluster using agent instrumentation). I've been working on the last one, using SkyWalking for K8s monitoring in HPE GreenLake for Private Cloud Enterprise. This monitoring is using different approach, kube-state-metrics for K8s metrics, OpenTelemetry collector / receiver for K8s monitoring. With another seperate blog from Thirukkannan (for infrastructure monitoring), we will have the full coverage using SkyWalking for HPE GreenLake monitoring.

2023-01-05 12:06 UTC, choukden requested changes
Hi Guoping, 
I have just added one additional comment for the conclusion of the post, now that I better understand what are the posts that are part of your APM monitoring series.

Denis

2023-01-05 12:06 UTC, choukden commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +This blog post is the first of three in a series. In the following posts, I will show you the detailed process how to set up the *Apache SkyWalking*, as the APM tool, in HPE GreenLake for Private Clo
Hi Guoping, now that I better understand what are the blog posts that are part of the series, how about this suggestion for edits:

"This blog post is the first of three in a series. In the following post, I will show you the detailed process on [how to set up the ***Apache SkyWalking*** APM tool in HPE GreenLake for Private Cloud Enterprise](https://developer.hpe.com/blog/set-up-apache-skywalking-for-k8s-and-vm-monitoring-in-hpe-greenlake-private-cloud/) for monitoring and alerting both customer application and Kubernetes cluster. Finally, I will expand on using Apache SkyWalking APM tool [to monitor the ***Online Boutique*** microservices application deployed across the hybrid cloud environment](https://developer.hpe.com/blog/monitor-application-performance-across-hybrid-cloud-environment-using-apache-skywalking-and-service-mesh/).

Notice that Dale might have a better idea.

What do you think?
Denis

2023-01-05 18:33 UTC, choukden requested changes
Hi Guoping,

Now that I have a better idea of the two blog post series, I am adding a suggestion for the last paragraph of the Conclusion section.

This blog post is the first of three in a series. [In the second post of the series](https://developer.hpe.com/blog/set-up-apache-skywalking-for-k8s-and-vm-monitoring-in-hpe-greenlake-private-cloud/), I will show you the detailed process on how to set up the Apache SkyWalking APM tool for monitoring and alerting of customer applications deployed on Kubernetes cluster provisioned on HPE GreenLake for Private Cloud Enterprise. [In the last (or third) post of the series](https://developer.hpe.com/blog/set-up-apache-skywalking-for-k8s-monitoring-in-hpe-greenlake-for-private-cloud-enterprise/), I will expand on setting up Apache SkyWalking APM tool to monitor the infrastructure of Kubernetes clusters deployed on HPE GreenLake for Private Cloud Enterprise.

Feel free to adjust as appropriate.

Thanks,

Denis.

2023-01-05 18:33 UTC, choukden commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +This blog post is the first of three in a series. In the following posts, I will show you the detailed process how to set up the *Apache SkyWalking*, as the APM tool, in HPE GreenLake for Private Clo
@GuopingJia 

Based on our discussion in the call today, I think one suggestion would be:

This blog post is the first of three in a series. [In the second post of the series](https://developer.hpe.com/blog/set-up-apache-skywalking-for-k8s-and-vm-monitoring-in-hpe-greenlake-private-cloud/), I will show you the detailed process on how to set up the Apache SkyWalking APM tool for monitoring and alerting of customer applications deployed on Kubernetes cluster provisioned on HPE GreenLake for Private Cloud Enterprise. [In the last (or third) post of the series](https://developer.hpe.com/blog/set-up-apache-skywalking-for-k8s-monitoring-in-hpe-greenlake-for-private-cloud-enterprise/), I will expand on setting up Apache SkyWalking APM tool to monitor the infrastructure of Kubernetes clusters deployed on HPE GreenLake for Private Cloud Enterprise.

2023-01-06 14:40 UTC, GuopingJia commented
Thanks Denis !

The new patch has addressed your comments on the Conclusion section. 

Guoping

2023-01-09 23:08 UTC, drensing reviewed
I did have a lot of comments in this blog post, but I hope they help you. This is such a great , informative post - I just want it to be crystal clear in everything you are trying to say. (and, to be fair, it was a long blog post anyway :-) 

All the best,
Dale

2023-01-09 23:08 UTC, drensing commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +Apache SkyWalking is an open source tool with *21K* GitHub stars and *6K* GitHub forks. In [StackShare community](https://stackshare.io/apache-skywalking#stacks.), Apache SkyWalking does not yet have
In the first sentence, change "does not yet have many approval" to something like "does not yet have much approval" or "does not yet have as broad an acceptence, only being..." or "does not yet have as great a share of the market..." (that last one might be the most appropriate.

2023-01-09 23:08 UTC, drensing commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +Apache SkyWalking is the first open source project that initialized and implemented an [Envoy Access Log Service (ALS)](https://www.envoyproxy.io/docs/envoy/v1.18.2/api-v2/service/accesslog/v2/als.pr
2nd sentence, add a hyphen between "language" and "specific" so it says "... language-specific technology."

3rd sentence, change "users could get" to "users **can** get".

Last sentence, change to "for monitoring and visualizing applicatio**ns** that **consist** of..."

2023-01-09 23:08 UTC, drensing commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +Apache SkyWalking is lightweight, scalable, and supports alerting and visualization. It can be easily set up as a *self-managed* APM tool within an on-premises data center. This avoids leasing custom
Rewrite the first sentence to "Apache SkyWalking is lightweight and scalable, and it supports alerting and visualization." Or, divide it out into two sentences.

Last sentence, add a hyphen between "third" and "party". Change the ending to "...in **the user's** environment."

2023-01-09 23:08 UTC, drensing commented on content/blog/get-started-with-application-performance-monitoring-tools-overview.md
> +This blog post gave a closer look at some of the best APM tools, either open-source or commercial vendor based. It listed the key features of each APM tool, and discussed in details their strengths a
Suggested rephrasing for the conclusion:
"In this blog post, I hope I gave you a closer look at some of the best APM tools that are out there, both open-source and commercial vendor based. In it, I have listed the key features of each APM tool and discussed each toll's strengths and weaknesses." (you can keep the next two sentences just as they are :-) )

2023-01-10 13:49 UTC, GuopingJia commented
> I did have a lot of comments in this blog post, but I hope they help you. This is such a great , informative post - I just want it to be crystal clear in everything you are trying to say. (and, to be fair, it was a long blog post anyway :-)
> 
> All the best, Dale

Hi, Dale, 

Thank you for spending time reviewing my blog. Yes, it's a very long blog post and I spent a lot of time walking through all related tools, understanding/comparing the difference. Huge amount of contents could easily get me lost. When I was finished it, I was thinking about your review comments. I appreciate your comments and a long list of very good suggestions !

The new patch should address all your comments. But let me know if there is anything you want me to change.

Guoping

2023-01-10 14:44 UTC, drensing reviewed
Thank you for incorporating my requested changes! I know there were a lot, but you did a great job.

All the best,
Dale

2023-01-30 17:43 UTC, GuopingJia commented
The new patch has addressed one comment from Fred.

2023-02-01 19:02 UTC, merged