Create Blog “getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk”
hpe-dev-incubator/hpe-dev-portal pull request #2029
Opened 2023-08-08 09:42 UTC by tbeha

Automatically generated by Netlify CMS

2023-08-08 16:53 UTC, choukden requested changes
Hi Thomas,

Thank you very much for your contribution to the HPE Developer Community portal.
This is a great blog post. I provided you with a few minor suggestions for changes.

Dale Rensing, our editorial consultant, will go through the editorial review in the coming days or so. Please expect additional suggestion for edit.

Here are some tips to assist you with the review of the suggestions and how to acknowledge them in GitHub:

- Navigate to **File Changed** area to visualize the comments from start to the end (You may see “Load Diff” for large blog post entry, in this case just click “Load Diff”), or navigate to **Conversation** area to visualize the comments per reviewer.

- As you incorporate the suggestions for edit in your blog post, please click on button **Resolve Conversation** in GitHub for each suggestion you incorporated.

Note we recommend you to continue doing edits of the blog post entry in the CMS Workflow editor while the entry is in the "**In Review**" column. Moving it back to the "**Drafts**" column will close the Pull Request (PR) in Github and when moving the entry to the “In Review” column again a new PR in Github is created, and we will lose the suggestions for edits.

Best regards,

Denis

2023-08-08 16:53 UTC, choukden commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +The Data Services Cloud Console (DSCC) UI might be sufficient for many customer (maybe even most of them), but lately I was approached from multiple customer that were looking for an efficient way to
on the [HPE Developer Community portal](https://developer.hpe.com/)

2023-08-08 16:53 UTC, choukden commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +The DSCC provides an public Open API 3.X spec that can be used to generate your preferred language SDK as it is described for Python in this [blog](https://developer.hpe.com/blog/get-started-building
The DSCC provides a public OpenAPI 3.X specification that can ...

Second sentence: Using the OpenAPI 3.X specification of the DSCC API ...

I think OpenAPI is spelled in 1 word.

Also, is it OpenAPi 3.X (capital X) or 3.x (lowercase x)? For consistence throughout the blog post, I would go with 3.x.

2023-08-08 16:53 UTC, choukden commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +My first step to generate the DSCC Powershell SDK was to download the current [YAML](https://console-us1.data.cloud.hpe.com/doc/api/v1/storage-api.yaml)- or [JSON](https://console-us1.data.cloud.hpe.
OpenAPI 3.x specification of the DSCC API...

2023-08-08 16:53 UTC, choukden commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +There are multiple generators available to create a SDK out of the Open API spec. I had at the end the best result with [openapi-generator-cli-6.6.0.jar](https://repo1.maven.org/maven2/org/openapitoo
out of the OpenAPI spec.

2023-08-08 16:53 UTC, choukden commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +In conclusion, the DSCC PowerShell SDK, derived from the DSCC Open API 3.x spec, includes at the time of writing this blog already 349 commands that can be used to manage your storage with  the DSCC
from the DSCC OpenAPI 3.x spec, ...
the most current DSCC OpenAPI 3.x spec...

2023-08-09 14:01 UTC, drensing commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +If I want to create for instance a new volume, then I do need to define the volume parameters like name, size etc. and the system where I want to create the volume. The system is defined by its syste
Modify this first sentence to:
" For instance, if you want to create a new volume, then you need to define the volume parameters, like name, size, etc., and the system where you want to create the volume."

You need to stick with the pronoun of the subject you've been using. There's a lot of switching back and forth and it gets confusing to the reader.

2023-08-09 14:39 UTC, drensing commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +T﻿he *Invoke-VolumeCreate* command will return the information of the generated task. You can use the *Get-Task* command to monitor the the progress of this task.
There are two "the"'s in the second sentence. Please remove one of them (just prior to "progress")

2023-08-09 14:39 UTC, drensing commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +These are the steps, I used to create a new Volume on my Primera 650 array with a name of DSCC-API-Vol and a size of 16GB.
Remove the comma. Not required in this case.

2023-08-09 14:41 UTC, drensing commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +In conclusion, the DSCC PowerShell SDK, derived from the DSCC Open API 3.x spec, includes at the time of writing this blog already 349 commands that can be used to manage your storage with  the DSCC
Modify the second sentence to read:
"At the moment, it is the most complete..."

For the last sentence, make "customer" plural.

2023-08-09 14:43 UTC, drensing commented on content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
> +I﻿ hope that the above examples will help in getting you started with the DSCC PowerShell SDK. While I have not tested every possible command, I did not find any issues in the SDK working on the exte
I would simplify this first sentence to:
"I hope the above examples help get you started with the DSCC PowerShell SDK."

For the second sentence, I would modify it to:
"While I have not tested every possible command, I have not found any issues in working with the SDK on the extensive daily tasks list received from my customer."

2023-08-17 12:52 UTC, merged