Create Blog “streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics”
hpe-dev-incubator/hpe-dev-portal pull request #2094
Opened 2023-09-26 18:57 UTC by joann-starke

Automatically generated by Netlify CMS

2023-09-27 12:42 UTC, choukden requested changes
Hi Joann, Abhishek, 

Thank you very much for your second post of the blog series about HPE Ezmeral UA. This is a great series.

Here are some "technical" feedback.
Dale will go through the editorial review in the coming day or so. So expect additional suggestions for edit in the coming days.

Here are some tips to assist you with the review of the suggestions and how to acknowledge them in GitHub:

- Navigate to **File Changed** area to visualize the comments from start to the end,or navigate to **Conversation area** to visualize the comments per reviewer.

- As you incorporate the suggestions for edit in your blog post, please click on button **Resolve Conversation** in GitHub for each suggestion you incorporated.

Note we recommend you to continue doing edits of the blog post entry in the CMS Workflow editor while the entry is in the "**In Review"** column. Moving it back to the "**Drafts**" column will close the Pull Request (PR) in GitHub and when moving the entry to the “In Review” column again a new PR in GitHub is created, and we will lose the suggestions for edits.

Thanks again, 
Best regards,
Denis

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +  - "opensource hpe-ezmeral data-ml-engineer data-scientist "
Hi Joann, Abhishek,

For Tag, please make sure to use separate tags (in the CMS editor, at the bottom of the editor, click "Add Tags" to include individual tag):
- opensource
- hpe-ezmeral
- data-ml-engineer
- data-scientist

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +<!--StartFragment-->
In the CMS Editor, in Markdown mode, please delete this XML code \<!--StartFragment--\>

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +This is part two of a blog series that showcases the capabilities of [HPE Ezmeral Unified Analytics](https://www.hpe.com/us/en/hpe-ezmeral-unified-analytics.html) through the real-world example of st
The URL https://www.hpe.com/us/en/hpe-ezmeral-unified-analytics.html give an error message. Could you please confirm the URL?

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Step 1: Data Gathering\
Please remove the backslash after Step 1: Data Gathering; Step 2: Data Preprocessing, Step3: Modeling, 
Just insert a carriage return between the Step and the description sentence.

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +MLflow consists of several key components:\
Please remove the backslash after MLFlow consists of several key components:

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +\
Delete the backslash, and just add a carriage return.

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +The models deployed into production are constantly monitored to identify inconsistencies and degradation in performance. Because models can skew to the old data used for training resulting in under p
In this section, please check occurrences of "Kube Flow": Is it Kube Flow or Kubeflow?

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +In the Kube Flow UI, “stock_pipeline_run” would be triggered to provide a green-red status of each step as it executes. 
Use escape character for the underscore in the "stock_pipeline_run":
stock\\_pipeline\\_run

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Seamless Integration: HPE Ezmeral Unified Analytics offers seamless integration of various data engineering and ML components like Spark, EzPresto, Superset, MLflow, Kube Flow. This integration strea
In the Conclusion section, is it Kube Flow or Kubeflow?

2023-09-27 12:42 UTC, choukden commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Reproducibility: Kube Flow ensures reproducibility by allowing users to define and version their entire ML pipelines using HPE Ezmeral Unified Analytics. This means that every step, from data prepara
For Reproducibility, do you mean Kube Flow or MLFlow?

2023-10-02 18:36 UTC, drensing reviewed
There you go! Second blog post reviewed.

All the best,
Dale

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +On the Web UI for MLflow, we can access multiple runs of the ML experiment for different parameter combinations. Details of the run can be accessed by clicking on the corresponding run name.
Change "we" to "you" in the first sentence. "We" don't use the "royal we" :-) in our blog posts.

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Model performance can be obtained by comparing various runs. In the image below, all six runs have been selected and we see that the model with epochs=20, performs best with the least loss and mean a
Change "we see" to "you can see"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +**Code Repository**
Change to "Code respository"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +**Model Deployment**
Change to "Model deployment"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +The next step is to deploy the best model chosen from the MLflow experiment. Here we are using KServe which is a standard Model Inference Platform on Kubernetes, built for highly scalable use cases.
Change the second sentence to read:
Here, Kserve, which is a standard model inference platform on Kubernetes that is build for highly scalable use cases, is being used. (I know... many prefer the active tense, but sometimes it's hard to get around the Royal We.

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +2. Multi-Framework Support: KServe supports serving models trained in various machine learning frameworks, such as Tensor Flow, PyTorch, scikit-learn, and others.
Use "Multi-framework support:"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +3. Advanced Deployment Strategies: KServe supports various deployment strategies, for example  Canary deployments or Blue-Green deployments,  allowing you to roll out new model versions gradually and
Use "Advanced deployment strategies:"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +4. Monitoring and Metrics: It provides metrics and monitoring capabilities, allowing you to keep track of model performance, errors, and other relevant statistics.
Use "Monitoring and metrics:"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +6. Integration with Kube Flow Pipelines: If you're using Kube Flow Pipelines for end-to-end machine learning workflows, KServe can be integrated seamlessly to deploy models as part of your pipeline.
I think Denis had a question as to whether Kube Flow was one word (KubeFlow) or not

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Next, a new model server must be created in Kube Flow and the yaml file uploaded. The inference service is created and once it is running, we can send our test data through REST APIs and get the resp
Change the last sentence to read:
"...once it is running, you can send your test data through REST APIs to..."

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +**Model Retraining**
Use "Model retraining"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +To prepare the Kube Flow pipelines, we have to define each task as a function. First “read_data()” is defined to read the input file from the data volume on the Kube Flow pipeline.
Kube Flow question
To avoid the Royal We, try this:
"To prepare the KubeFlow pipelines, define each task as a function."

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Once defined, functions are converted into a Kube Flow component using “create_component_from_func()”.
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Once each of the tasks are defined, the Kube Flow pipelines are defined to call each of the steps using DSL (Domain Specific Language).
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +When the Kube Flow pipeline is set up, the pipeline can run using the Kube Flow client where the required arguments and parameters are passed for the specific run.
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +![](/img/kubeflow-setup-run.png "Figure 13. Kube Flow client is created and executed with appropriate arguments. ")
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +In the Kube Flow UI, “stock_pipeline_run” would be triggered to provide a green-red status of each step as it executes. 
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +From the above example, HPE Ezmeral Unified Analytics has significantly enhanced the end-to-end pipeline of financial service use cases by providing a comprehensive platform tailored to the specific
I'd recommend combining these two paragraphs to read something like this:

As you can see, HPE Ezmeral Unified Analytics has significantly enhanced the end-to-end pipeline of the financial service use cases by providing a comprehensive platform tailored to the specific needs of ML practitioners and data scientists. HPE Ezmeral Unified Analytics offers seamless integration of various data engineering and ML components, like Spark, EzPresto, Superset, MLflow, and Kube Flow. This integration streamlines the entire ML workflow, reducing friction between dissimilar stages and enables more efficient development of ML pipelines. 

In summary: (and then it goes to your bullets)

(or something like that at the end... feels like it's missing a few words at the very end. Also, you didn't need "Here is a conclusion highlighting the benefits of..."

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Seamless Integration: HPE Ezmeral Unified Analytics offers seamless integration of various data engineering and ML components like Spark, EzPresto, Superset, MLflow, Kube Flow. This integration strea
Use "Seamless integration:"

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Scalability: Kube Flow on HPE Ezmeral Unified Analytics excels at scaling applications. Kube Flow leverages this capability to scale ML workloads as needed, handling large datasets and complex models
Kube Flow?

2023-10-02 18:36 UTC, drensing commented on content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
> +Automated Workflow Orchestration: Kube Flow Pipelines simplifies the orchestration of ML workflows as code. With HPE Unified Analytics, this automation reduces manual effort, enhances reproducibility
Use "Automated workflow orchestration:"
Kube Flow question
"Pipelines" should be "pipelines"
Question on HPE Unified Analytics or HPE Ezmeral Unified Analytics

2023-10-04 11:04 UTC, merged