Create Blog “streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible”
hpe-dev-incubator/hpe-dev-portal pull request #2281
Opened 2024-01-25 08:39 UTC by jullienl

Automatically generated by Netlify CMS

2024-01-25 13:23 UTC, choukden requested changes
Hi Lionel,

Thank you for your new blog post.
Just a minor suggestion for changes from me about naming convention for HPE GreenLake for COM.

Dale will go through the editorial review and you can expect additional suggestions for changes in the coming days or so.

Thanks,
Denis

2024-01-25 13:23 UTC, choukden commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +In the rapidly-evolving world of IT infrastructure management, achieving speed, efficiency, and reliability in server provisioning can make a significant difference. This is where cutting-edge tools
Brand name for COM is "HPE GreenLake for Compute Ops Management"
see: https://www.hpe.com/us/en/hpe-greenlake-compute-ops-management.html 

So you may want to slightly update the 2nd sentence of this paragraph and other occurrences of COM throughout the post to be compliant with Brand naming.

2024-01-25 14:03 UTC, Didier-Lalli requested changes
Merci Lio. Je reste un peu sur ma faim. 
Ca met bien valeur le boulot que tu as réalisé mais pas trop comment je peux moi, client, l'adapter à mon environment. Peut-être tu pourrais rajouter un chapitre à ce propos.

2024-01-25 14:03 UTC, Didier-Lalli commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +
It's a nice teaser, but how do I leverage this to use in MY environment. There could be a lot more to explain this like:

- Clone the repo
- then what?
-

2024-02-01 18:30 UTC, drensing reviewed
Great blog post, Jullien! Thank you!

Sorry it took me a bit longer to get to this.

All the best,
Dale

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +## Mastering Server Management with HPE GreenLake for Compute Ops Management
Change to "Mastering server management with HPE GreenLake for Compute Ops Management."

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +- **Automated Workflows**: Convert time-consuming manual processes into automated workflows that can be tracked and managed easily.
Change to "Automated workflows:"

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +- **Scalable Infrastructure**: Embrace growth without compromising on performance or manageability.
Change to "Scalable infrastructure: Embrace growth without compromising performance or manageability." (sentence case and remove the word "on")

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +- **Reduced Human Error**: Minimize mistakes by standardizing server configurations across the board.
Change to "Reducing human error: "

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +A key attribute of Ansible that I sought in this project is its impressive capability to execute tasks concurrently across numerous systems, thereby accelerating deployment processes. This feature is
Change the word "standout" to "outstanding" so it reads "...among Ansible's outstanding functionalities, enhancing..."

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +## Explore My Video Series
Change to "Explore my video series"

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +Join me on my [GitHub repository](https://github.com/jullienl/HPE-COM-baremetal), where a wealth of information awaits you in the README file. Learn how to effectively utilize this project, from clon
Change to "...to commencing **with** its use,..."

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +Get started now, and begin transforming your server deployment strategy today!
Remove the comma

2024-02-01 18:30 UTC, drensing commented on content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
> +Stay tuned as I will continue to update and maintain this project, incorporating user [feedback](mailto:lio@hpe.com)   and the latest advancements that HPE GreenLake will offer.
Take out the word "will" and just say "Stay tuned as I continue to update..."

2024-02-21 15:27 UTC, jullienl commented
I've just made a number of changes to the blog in response to Didier's pertinent comment

2024-02-22 12:17 UTC, merged