Create Blog “why-is-redfish®-different-from-other-rest-apis-part-1”
hpe-dev-incubator/hpe-dev-portal pull request #2341
Opened 2024-02-19 17:00 UTC by donzef

Automatically generated by Netlify CMS

2024-02-21 22:59 UTC, drensing reviewed
Lovely blog post, Francois!

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Redfish® is a low level management RESTful API standardized by the Distributed Management Task Force (<a href="https://dmtf.org" target="_blank">DMTF</a>) consortium. DMTF publishes several standards
place a hyphen between "low" and "level" so it's "low-level"

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Redfish® is born in August 2015. As of today, more than <a href="https://dmtf.org/about/list" target="_blank">sixty members</a> contribute to its development: computer makers, storage and network dev
If you keep this statement as is, you still need to change "is" to "was" (past tense). However, I think you might actually want to reword it to something like:
"Redfish made its first appearance in August 2015." or "Redfish was first introduced in August 2015."

Change "A funny story says that" to "A funny story relates how "Redfish" comes from..."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The main goal of Redfish® is to replace the Intelligent Platform Management Interface (<a href="https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-home.html" target="_blank">IMPI
Modify the first sentence to read:
"The main **reason Redfish was introduced was** to replace the..."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The adoption of this standard across the industry has been very quick and this article is an attempt to explain some of the specificities that have contributed to this success.
Change "this success" to "its success"

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Redfish® is classified as a RESTful API as all the fundamentals are present, like a service/client model, HTTPS JSON formatted requests transferring representational states from and to identified end
Shouldn't it be a client/server model?

Where you have the second comma in the first sentence, replace it with the word "and" so it reads:
"...all the fundamentals are present, like a client/server model and HTTPS JSON Formatted requests that transfer representational states from and to identified end points."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The Redfish® service is included in the server management controller firmware and cannot be separated from it. In this article, I will name this controller “BMC”, for “Baseboard Management Controller
In the 3rd sentence, change the word "which" to "that" so it reads "...has a BMC that starts as soon..."

Also change the "which" in the second to last sentence to "that"

https://www.grammarly.com/blog/which-vs-that/

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +In most cases, Redfish® clients performs <a href="https://en.wikipedia.org/wiki/Out-of-band_management" target="_blank">out-of-band management</a>. However, it is entirely possible to install the cli
Change "performs" to "perform" (subject/verb agreement).

Place a comma before "which" in the last sentence.

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The Redfish® protocol specification is published in DMTF document <a href="https://www.dmtf.org/dsp/DSP0266" target="_blank">DSP0266</a> while data modeling in <a href="https://www.dmtf.org/dsp/DSP02
I think you're missing a word in the first sentence. It also needs a comma. I think it should read "...document DSP0266, while data modeling **is in** DSP0268."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +* We also find very practical things like the ways to authenticate (basic authentication, session token, etc.) and the endpoints where authentication is necessary (everywhere except at the root `/red
Modify this to "Some very practical things like the ways...

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +* Surprising things like receiving an "error" messages for successful requests. Figure 2 shows the successful erasure of a storage logical volume (LUN) whose response contains the `error{}` object wi
Change "messages" to "message". (since you placed "an" in front of "error", you make it singular)

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Responses to Redfish® requests consist of JSON packets containing key/value properties defined by the DMTF in a schema file. This name of schema files is contained in the `@odata.type` property that
I don't quite understand what you mean by "This name of scheme files". Maybe it should be "file"?

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +For example, the schema defining the root of the Redfish® tree is `#ServiceRoot`. Its full name returned by `curl -sk https://bmc-ip/redfish/v1 | jq '."@odata.type"'` is: `#ServiceRoot.v1_13_0.Servic
In the third sentence, change "which, in this specific case..." to "that, in this specific case..."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +With a close look to the Redfish® root diagram in (Figure 3), you will notice the presence of endpoints allowing access to the modeling of the server subsystems. For example, the `Chassis{}` object p
Place a comma before "which contains the exhaustive..."
Remove "the" prior to "URIs"

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Computer makers have the possibility of modeling proprietary properties (not standardized) and constituting added value compared to the competition. For example, HPE iLO can store firmware updates be
I'd reword this first sentence to:
"Computer makers are able to model proprietary properties (not standardized), which constitutes added value compared to the competition."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Another example: An HPE ProLiant server containing a storage enclosure connected to a (“modern”) storage controller is represented by two members in the chassis collection. A member pointing to the c
The last sentence in this paragraph is not a complete sentence. Consider rephrasing it or appending it to the previous sentence by changing the period after "the chassis collection" to a semi-colon ";" and changing "A member" to "a member"

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The naming of collection members is specific to each implementation of the Redfish® service. The BMC endpoint for an HPE server of type ProLiant is: `/redfish/v1/Managers/1`. That of an OpenBMC is: `
Modify the second sentence to read:
"The BMC endpoint for an HPE ProLiant server is:..."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +The naming flexibility given to Redfish® services generates extra work for client developers: their code has to discover the names of collection members before being able to access their properties.
oh! well, that's a problem, isn't it... when it fails after a firmware update!

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Figure 7 is extracted from a BIOS registry which has the effect of prohibiting the activation of Windows secure mode support if the server does not contain a TPM (Trusted Platform Module). It is inte
Change "which" to "that"

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +These URIs contain links to all schemas and registries used by the service. They point to documents stored in the BMC, if it has the storage capacity, or to the official DMTF website. In the later ca
In the third sentence, I think you mean "In the latter case,..." And you might mean "must have a means to access the Internet"

In the final sentence, it should probably read:
"They are helpful to identify..." (don't need the word "be")

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +After verification, the client code can change (PATCH) the properties marked as `ReadOnly=False` in the schema. The main server chassis in Figure 9 shows the PATCH method and the IndicatorLED propert
Change "we" to "one" where it reads "(Figure 10), so one should be able to perform..."

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +Over time, certain properties are deprecated. This information is mentioned in the schemas. Thus, clients receiving a “property not found” response will be able to consult the schema and check if by
lol... "I don't understand, it worked before!" (love it!)

2024-02-21 22:59 UTC, drensing commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
> +However, Redfish® is full of other particularities, conceptual and practical, which are very interesting to study. For example the mode of communication with additional storage or network cards, upda
Hmmm... that second sentence isn't a complete sentence... in spite of how long it is.  You need a subject and a verb...

2024-02-23 10:05 UTC, choukden requested changes
Hi Francois,
Sorry for the delay for review of your part 1 of the series.
This looks great to me. I learned a lot about RedFish!
Just one minor comment about the blog post you are referring in the post abut Hypermedia API concept.

Let us know once you have took into account all the suggestions for edits.

We will wait for the second part review and readiness to publish the series.

Thanks
Denis

2024-03-07 09:27 UTC, merged