Create Blog “why-is-redfish®-different-from-other-rest-apis-part-2”
hpe-dev-incubator/hpe-dev-portal pull request #2352
Opened 2024-02-22 17:39 UTC by donzef

Automatically generated by Netlify CMS

2024-02-23 13:02 UTC, choukden requested changes
Hi Francois,

a few comments for you to take into consideration,

As for the bullet item list, you may want to use the style below to format the bullet list items in "standards" text.

<style>
li {
   font-size: 27px;
   line-height: 33px;
   max-width: none;
}
</style>

Just put the style at the top of your blog post. The bullet list will then be rendered as the same font as the rest of the content. 
In the CMS editor, on the right, you will see the font larger than the rest of the content. This is normal. No problem with the font. the final rendering will be correct at the time of publishing of the post.

You may want to apply the same on Part 1 of the series.

Thanks,
Denis

2024-03-01 19:07 UTC, drensing reviewed
Hi, Francois. Grammatically, pretty good! I'm teaching you a new lesson with this one - the proper use of R-balls.

But I have to say that the introduction was confusing to me and the summary was lacking a little in why this is a benefit.

Remember that our readers don't always read Part 1s and Part 2s consecutively. They might just stumble up Part 2 as the first one they've seen. You'll want to make sure you hook them in with each blog post, providing them with enough context to want to read more.

Sorry it took me a little while to get to this. Love seeing your submissions!
Dale

2024-03-05 10:17 UTC, donzef commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-2.md
> +Redfish® resources support the GET request to retrieve their current state. Modifications or deletions can be performed to certain resources using POST, PUT, PATCH and DELETE requests. Until then, no
Removed "Until then": this was a bad translation from French.

2024-03-05 10:32 UTC, donzef commented on content/blog/why-is-redfish®-different-from-other-rest-apis-part-2.md
> +However, other types of operations are difficult to model with classic HTTP requests. For example, it is impossible to "read" the server's power button to know its status! Asking for the "return to f
Hopefully addressed.

2024-03-05 15:17 UTC, donzef commented
Thanks Dale for the R-ball rule. It is clear now!

May be a quick final review with focus on the intro and the summary, to make sure I did not introduce other typos. Thanks.

2024-03-07 09:26 UTC, merged