Create Blog “getting-started-with-hpe-greenlake-api-for-backup-and-recovery”
hpe-dev-incubator/hpe-dev-portal pull request #2458
Opened 2024-04-09 23:40 UTC by rondharma

Automatically generated by Netlify CMS

2024-04-16 16:49 UTC, choukden requested changes
Hi Ron,

Thank you so much for your 3rd part of the API Family for the Data Services.

I have added a few comments and suggestions for you to consider.
Also, please make sure to click on "Resolve conversation" so we know you took into account the suggestion and comment.

 
Make sure to add "HPE" in front of GreenLake throughout your post.

Also, to avoid issue with formatting of numbered item, bullet items I woudl suggest you to use the tip below:

Insert the following Style statement in your markdown at the beginning of your post. This will forma the numbered list and bullet list to standard text size. 
Please note that you may see bigger fonts in the CMS editor for bullet items/numbered items in the right side of the editor.  You can ignore it. The rendering of the post will be good in the "preview".  All the text will be formatted to standard text size.

<style>
li {
   font-size: 27px;
   line-height: 33px;
   max-width: none;
}
</style>
 

**Reference:** https://github.com/hpe-dev-incubator/hpe-dev-portal/blob/master/docs/ContributorGuide-v2.md#tips-and-trick-using-the-cms-editor
**See Tip #16**

Thanks again Ron for your great effort to come up with this series of blog posts.

Let's wait for Dale's editorial review - She is going to review your blog post series in a day or so.

Best regards,

Denis

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +The second part of the GreenLake API for Backup Recovery resources is the resources from which HPE GreenLake for Backup and Recovery provides protection for data loss. In below diagram, you will see
--> ...of the HPE GreenLake API for ...

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> In the current HPE Developer website, there is a single resource categorized as v1alpha1 that will be used to register, unregister, and update the hypervisor-manager. The current supported hypervis
--> In the current HPE GreenLake Developer website, there is a....

--> The hypervisor-manager enabled HPE GreenLake Backup and Recovery to discover the VMware vCenter which controls the assets for data protection.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +There are other resources exist in the HPE GreenLake for Backup and Recovery that are not mentioned above; however, they are available in the user-interface for HPE GreenLake for Backup and Recovery.
--> There are other resources that exist in the HPE GreenLake for Backup and Recovery..

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Additionally, there is also a resource called a protection job that is not shown in the user-interface; however, it is required to perform the operation of data protection. You will need to manipulat
Do you mean "not shown" in the UI or "shown" in the UI? It is not clear to me because the image below seems to show protection jobs.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Beyond protection-jobs, there are recovery points (also known as copies). These are resources that used to represent a copy that is inside the protection store, and they are used to perform the recov
--> These are resources that are used to represent a copy...

--> Microsoft Azure

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +This set of Backup and Recovery APIs use the same authorization and permission as the rest of the family of HPE GreenLake API for data services. To ensure that all programmatic interaction with the H
Suggest to add one or more line space(s) to make the reading easier for this paragraph.

--> Nevertheless, there is also blog [post](https://developer.hpe.com/blog/learn-what-you-can-do-with-hpe-data-services-cloud-console-api-in-just-3-minutes/) that describes how to use publicly available tool to manipulate this API without a programming language,

Add a space after the Blog post Hotlink and the word "that"

You may want to use backtick or italics for the command: GET /backup-recovery/v1beta1/protection-jobs 

---> last sentence: The documentation page also provides the ability to execute the API directly on the documentation page as explained in the previous blog [post](https://developer.hpe.com/blog/getting-started-with-hpe-greenlake-api-for-data-services/)(Getting started with HP GreenLake Data Services API).

Add a space after the hotlink for the post.
And the title for your first post is "Getting started with HPE GreenLake APIs for Data Services".

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +*The above figure shows the three-pane of the interactive API reference documentation for one of HPE GreenLake API for Backup and Recovery.*
typo: the three-panel of the....

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +A protection store is the critical resource that is required to store the recovery points on-premises and in the cloud. The cloud protection stores are created on top of either the Protection Store G
--> Microsoft Azure cloud storage.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +*T﻿he figure above shows the user interface used to create a cloud store protection at Azure in eastus2 storage location using the user interface.*
--> Microsoft Azure

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +The list of the steps to perform this use case using GreenLake API
--> ...using HPE GreenLake API.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +6. Finally, I created of the protection policies using the GreenLake API for Backup and Recovery **POST /backup-recovery/v1beta1/protection-policies**, and I used the above JSON structure in the requ
...using the HPE GreenLake API for...

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +7. The below figure shows the complete response JSON body from the above API that shows the construction of the protection policy with different protection tiers and the schedules associated with the
Suggestion to not make the item 7 a numbered item. Just remove the "7.". 

Please check the preview: https://deploy-preview-2458--hpe-dev-portal.netlify.app/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery/

You will see that the values for ID, Snapshot, On-premises and Cloud are listed as numbered item. They should just be listed as bullet items in the list.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +1. I obtained the values from **virtual machine id, name, and type** keys which were going to be used as the key-pair values required for the key **assetInfo** as shown in below figures. To obtain th
Check the hotlink for API.

I obtained the values from virtual machine id, name, and type keys which were going to be used as the key-pair values required for the key assetInfo as shown in below figures. To obtain those, I used the HPE GreenLake [API](https://developer.greenlake.hpe.com/docs/greenlake/services/virtualization/public/openapi/virtualization-public-v1beta1/tag/virtual-machines/) for virtualization to discover the detail information of a virtual machine “0-Linux-Demo-VM02”. 

Please check your markdown, there is a backslash in front of [API] and the parenthese is missing.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +3. The GreenLake API to accomplish the use case above was **POST /backup-recovery/v1beta1/protection-jobs/:id/run**, and the documentation of this [API](https://developer.greenlake.hpe.com/docs/green
The HPE GreenLake API to accomplish...

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Each of the recovery points regardless of the location of store (array snapshot, On-Premises Protection-Store, or HPE Cloud Protection-Store) can be recovered using this GreenLake API: **POST /backup
...using this HPE GreenLake API...

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +2. Obtain the Cloud Recovery Protection Id from the for the cloud protection recovery from the virtual machine using the GreenLake API GET /backup-recovery/v1beta1/virtual-machines/:id/backups given
using the HPE GreenLake API...

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +This blog provides the introduction of the new set of REST API from the family of the APIs for data services on HPE Greenlake, namely **HPE GreenLake API for Backup and Recovery**. This set of API is
Suggest to add a line space in this paragraph to make the reading easier.

2024-04-16 16:49 UTC, choukden commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Please don’t hesitate to explore this new set of API for Cloud Data Services on HPE GreenLake and see how you can improve your agility in managing your data. Any questions on HPE GreenLake Data Servi
Add a "period" at the end of this paragraph.

2024-04-18 19:00 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> ***Note:*** that I used a set of selection parameters in below figure to summarize the information from this task information:
Rephrase to:
Note: **I used** a set of selection parameters in **the figure below** to provide **a summary of this task information**."

2024-04-18 19:00 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> I copied the task’s id from the response header’s location value of the prior API execution into a Postman’s variable called `{{taskId}}`, and incorporated `{{taskId}}` variable to the `async-opera
Add the word "the" after "incorporated"

2024-04-18 19:01 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +5. For reference, I went into the Protection Stores menu as shown in the below figure to show that HPE GreenLake Backup and Recovery, and confirmed that the desired protection store was available.
"as shown in the figure below"

But there's something about the first part of this sentence that isn't clear... "to show that HPE GreenLake Backup and Recovery..." Something seems to be missing here.

2024-04-18 19:03 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +One of the common use-case that every user of HPE GreenLake Backup and Recovery will deploy is the creation of a protection-policy. This resource is important because it sets up the schedule for crea
change to read "A common use-case that every..."

Break up the second sentence into two. Place a period where you have a semi-colon. Start the next sentence with "Additionally, it sets up..."

2024-04-18 19:03 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +A protection policy contain several JSON objects that are displayed in the below figure.
"A protection policy contai**ns.**.."
"in the figure below."

2024-04-18 19:04 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +1. A Schedule that contains the frequency for creation of the copy and time to retain the copies.
Lowercase the "S" in "schedule".

2024-04-18 19:05 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +4. The pre-script information contains the link to the scripts to be executed prior to the creation of the copy.
Add the word "that" prior to "contains".

2024-04-18 19:05 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +5. The post-script information contains the link to the scripts to be executed after the creation of the copy.
Add the word "that" prior to "contains".

2024-04-18 19:05 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +﻿*The above figure shows the guide for protection-policies request body JSON structure*
Missing a period at the end?

2024-04-18 19:06 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +The list of the steps to create this protection policy:
Modify to read "**This is** the list of steps **used** to create this protection policy:"

2024-04-18 19:07 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +3. From the figure below, I used `GET /backup-recovery/v1beta1/protection-stores` [API](https://developer.greenlake.hpe.com/docs/greenlake/services/backup-recovery/public/openapi/backup-recovery-publ
At the very end, it should say "to provide **a** shorter response..."

2024-04-18 19:08 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +4. I repeat the same execution of the `GET /backup-recovery/v1beta1/protection-stores` to obtain the **“<cloud-protection-store-id>”**. To accomplish that, I used the following `filter: protectionSto
"I repeat**ed**" [past tense]

Again, later on in the paragraph "to provide **a** shorter response..."

2024-04-18 19:09 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> ***Note:*** I didn’t include objects for immutability, prescript, and postscript into the JSON structure. If it’s not intended, you don’t need to include unused key-pair values into the JSON struct
Do you always italicize your notes? I don't remember it that way. However you do it, be consistent.

2024-04-18 19:10 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +6. Finally, I created of the protection policies using the GreenLake API for Backup and Recovery `POST /backup-recovery/v1beta1/protection-policies`, and I used the above JSON structure in the reques
I think you mean "Finally, I created the protection policies" ("of" doesn't belong in here).

2024-04-18 19:11 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Next in the list of use cases for this blog post, I followed the progression for the day one activities. The next one is to protect a virtual machine which is applying this protection policy to a vir
Usually, we state it as "Day One".
In the second sentence, change "which is applying" to "that is applying"

2024-04-18 19:12 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +1. I obtained the values from `virtual machine id, name, and type` keys which were going to be used as the key-pair values required for the key `assetInfo` as shown in below figures. To obtain those,
Change "which" to "that" in the first sentence.
Should "for virtualization" be "for Virtualization"?

2024-04-18 19:13 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +2. I created a JSON structure of a request body for applying the protection policy against a virtual machine without a protection group to make a simple example for this blog post. Note that this JSO
"Each of this protection" grammatically, should be "Each of these protections"

2024-04-18 19:14 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> **Note:** As of March 2024, value of type from *virtualization/virtual-machine* was translated to *hybrid-cloud/virtual-machine*.
Yeah... see, this "Note" is not italicized.

2024-04-18 19:15 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> **Note**: that that the execution of this API will trigger a protection execution right after the execution of this API completed.
Take out both "that"s and just say "Note: The execution of this API...

2024-04-18 19:15 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +The below list detailed the required steps:
Simplify to "The below details the required steps:"

2024-04-18 19:17 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +2. This use case is equivalent to run now button at the schedule of the `“0-Linux-Demo-V02”` on the selected cloud protection as shown in below figure. After clicking `“Run Now”` button, a cloud prot
Instead of "On next step" say "In the next step"

2024-04-18 19:18 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +3. The GreenLake API to accomplish the use case above was `POST /backup-recovery/v1beta1/protection-jobs/:id/run`, and the documentation of this [API](https://developer.greenlake.hpe.com/docs/greenla
Add "HPE" in front of "GreenLake API". Add the word "used" prior to "to accomplish".
Change "list" to "lists".

Change "as the following" to "as follows:"

2024-04-18 19:19 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> **Note** that there was a key called `“fullBackup”` inside the JSON request body to enable the creation of full protection where a backup will be created independently from the existing copies in t
Take out the word "that" and just say "Note: There was a key..."
Add a comma prior to "which is cloud protection" in the second to last sentence.

2024-04-18 19:19 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +The activities above were validated from the HPE GreenLake Backup and Recovery list of the recovery points as shown in the below figure.
"as shown in the figure below."

2024-04-18 19:20 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Each of the recovery points regardless of the location of store (array snapshot, On-Premises Protection-Store, or HPE Cloud Protection-Store) can be recovered using this GreenLake API: `POST /backup-
Place commas around this phrase "regardless of the location of store (array snapshot, On-Premises Protection-Store, or HPE Cloud Protection-Store)"

Add "HPE" in front of "GreenLake API"

2024-04-18 19:23 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +5. To set the virtual machine network to the correct network port group, I glanced into the existing virtual machine `"0-Linux-Demo-V02"`, discovered the network port group `“Mgmt-DPortGroup”`. From
For the same reason, you'll need to change "I glanced into" to "you'll need to look into..., to discover the network..."

And so forth... here you have "I selected" again, you'd have to change this.

Consider again whether this whole section should be giving instructions or if you want to tell the story of how you did it and make the appropriate modifications.

2024-04-18 19:23 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +6. After I obtained all the values that were required to build the request body to recover a cloud recovery point from `“0-Linux-Demo-VM02"`, I constructed the JSON request body as shown in the below
Same note here regarding "voice"

2024-04-18 19:23 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +7. To validate that the recovery was completed, and I tracked the progress from the response using the `async-operations` [API](https://developer.greenlake.hpe.com/docs/greenlake/services/data-servic
Same note here regarding "voice"

2024-04-18 19:23 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +8. At the end, I went to the vCenter console to validate that the virtual machine 0-Linux-Demo-VN02-2-05-04-2024_05:48_PM was indeed part of the virtual machines inventory.
Same note here regarding "voice"

2024-04-18 19:25 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +This blog provides the introduction of the new set of REST API from the family of the APIs for data services on HPE Greenlake, namely **HPE GreenLake API for Backup and Recovery**. This set of API is
Modify to "This blog post introduces the new set of REST APIs in relation to the family of APIs for data services...

Second sentence, modify to "This set of APIs

Change "In this blog, I also introduced" to "In this post, I also introduced"

2024-04-18 19:25 UTC, drensing commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +Please don’t hesitate to explore this new set of API for Cloud Data Services on HPE GreenLake and see how you can improve your agility in managing your data. Any questions on HPE GreenLake Data Servi
Change "API" to "APIs in the first sentence.

2024-04-23 17:03 UTC, rondharma commented on content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
> +> You will see in this blog post that I used combination of HPE GreenLake APIs from [data services](https://developer.greenlake.hpe.com/docs/greenlake/services/data-services/public/guide/) and [virtu
Agree  Dale, but I like to keep everything in one topic together

2024-04-24 10:38 UTC, merged