Create Blog “redfish-interoperability-profiles”
hpe-dev-incubator/hpe-dev-portal pull request #2607
Opened 2024-07-03 11:02 UTC by donzef

Automatically generated by Netlify CMS

2024-07-03 13:03 UTC, choukden requested changes
Bonjour Francois

Thank you for your new contribution.
I have added a few comments
Images and some code snippets are not correctly rendered.

The preview link is:
https://deploy-preview-2607--hpe-dev-portal.netlify.app/blog/redfish-interoperability-profiles/

I have asked Fredo or Mathieu to go through the Technical review.
Dale will go through the editorial review.

THANKS!!

Denis

2024-07-03 13:03 UTC, choukden commented on content/blog/redfish-interoperability-profiles.md
> +```shell Interop Validator
The code snippet is not rendered correctly. Please check the language syntax

2024-07-03 13:03 UTC, choukden commented on content/blog/redfish-interoperability-profiles.md
> +```
Code snippet not correct

2024-07-03 13:03 UTC, choukden commented on content/blog/redfish-interoperability-profiles.md
> +```shell Configuration file
Code snippet not correct

2024-07-03 14:03 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Systems eligible by the OpenStack <a href="https://wiki.openstack.org/wiki/Ironic" target="_blank">Ironic</a> (bare metal machine provisioning) and the <a href="https://wiki.openstack.org/wiki/Valenc
Consider replacing to be started or stopped from remote. with to be powered on and off remotely

2024-07-03 14:04 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +When I explain to an audience that the <a href="https://redfish.dmtf.org" target="_blank">Redfish® standard</a>
looking at me with big eyes and this question in mind:  to be replaced by looking at me puzzled and asking themselves...

2024-07-03 14:07 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Flexibility is great, but too much flexibility can be a problem for standard organizations, sofware projects or end users willing to move from the Intelligent Platform Management Interface (<a href="
can be a problem for  to be replaced by can turn into or become an issue

2024-07-03 14:09 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Flexibility is great, but too much flexibility can be a problem for standard organizations, sofware projects or end users willing to move from the Intelligent Platform Management Interface (<a href="
to move **away** from the Intelligent Platform Management Interface (<a href="https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-home.html" target="_blank">IPMI</a>) to Redfish for hardware management.

2024-07-03 14:10 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Concerning standard organizations and software projects, the <a href="https://www.opencompute.org/about" target="_blank">Open Compute Project®</a> (OCP) and the <a href="https://wiki.openstack.org/wi
projects can only adopt Redfish as their preferred management technique   :  protocol innstead of technique ?? or technology

2024-07-03 14:12 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Concerning standard organizations and software projects, the <a href="https://www.opencompute.org/about" target="_blank">Open Compute Project®</a> (OCP) and the <a href="https://wiki.openstack.org/wi
could be implemented in or on their managed nodes???

2024-07-03 14:12 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Concerning standard organizations and software projects, the <a href="https://www.opencompute.org/about" target="_blank">Open Compute Project®</a> (OCP) and the <a href="https://wiki.openstack.org/wi
Dale would know better ;-)

2024-07-03 14:14 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Systems eligible by the OpenStack <a href="https://wiki.openstack.org/wiki/Ironic" target="_blank">Ironic</a> (bare metal machine provisioning) and the <a href="https://wiki.openstack.org/wiki/Valenc
Consider replacing Systems eligible by the OpenStack  with Systems supported by

2024-07-03 14:16 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +Redfish clients designed for managing multi-vendor systems have also a need for a list of mandatory and recommended features. For example, if a system cannot return the firmware version of its BMC, t
system cannot return the firmware version of its BMC  to be replaced by system cannot return its BMC's firmware version

2024-07-03 14:17 UTC, pattdepanick commented on content/blog/redfish-interoperability-profiles.md
> +The following example is a minimal profile created for didactic purpose. It is not relevant for use in a real life context.
It is not relevant for use in a real life context. to replaced by  It is not relevant for use in a proper production context.

2024-07-03 15:15 UTC, donzef commented
Reported issues hopefully resolved. Thanks. Waiting for Dale's review. No rush.

2024-07-08 17:00 UTC, drensing commented on content/blog/redfish-interoperability-profiles.md
> +Then, Interoperability Profiles could also be leveraged by the purchasing departments of large organizations with several computer suppliers. By including such Profiles in their Requests for Proposal
Recommend rewording this first sentence to:
Interoperability profiles can also be leveraged by purchasing departments of large organizations who have several computer suppliers. 

In the next sentence, change "could" to "can" (it's a more powerful word):
By including such profiles in their Request for Proposal (RFPs) documents, they can make sure that the computers they purchase...

The last sentence also needs some slight modification:
Having a clear knowledge of this baseline is **a** definite plus for security and supervising departments.

2024-07-12 15:35 UTC, donzef commented on content/blog/redfish-interoperability-profiles.md
> +## Redfish Interoperability Profiles
For now, I'll remove leading upper cases and ask for confirmation.

2024-07-12 15:49 UTC, donzef commented on content/blog/redfish-interoperability-profiles.md
> +The following code block clones the Validator GitHub repository and asks to create a configuration file and a Profile. Then it launches the Validator with those two files as input.
Aligned Interoperability Validator with Profiles: no upper case.

2024-07-12 16:07 UTC, donzef commented
Implemented Dale's suggestions. Thanks.

Still need to rewrite a bit the last paragraph (as per feedback received offline) and get technical review from Jeff Autor.

2024-07-12 16:08 UTC, drensing commented
[like]  Rensing, Dale reacted to your message:
________________________________
From: Francois Donze ***@***.***>
Sent: Friday, July 12, 2024 4:07:26 PM
To: hpe-dev-incubator/hpe-dev-portal ***@***.***>
Cc: Rensing, Dale ***@***.***>; Review requested ***@***.***>
Subject: Re: [hpe-dev-incubator/hpe-dev-portal] Create Blog “redfish-interoperability-profiles” (PR #2607)


Implemented Dale's suggestions. Thanks.

Still need to rewrite a bit the last paragraph (as per feedback received offline) and get technical review from Jeff Autor.

—
Reply to this email directly, view it on GitHub<https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/2607#issuecomment-2225895715>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASPH7RJBEONKSK77RP6RSC3ZL75L5AVCNFSM6AAAAABKJKREZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRVHA4TKNZRGU>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-07-12 16:10 UTC, drensing commented
[like]  Rensing, Dale reacted to your message:
________________________________
From: Francois Donze ***@***.***>
Sent: Friday, July 12, 2024 3:36:17 PM
To: hpe-dev-incubator/hpe-dev-portal ***@***.***>
Cc: Rensing, Dale ***@***.***>; Review requested ***@***.***>
Subject: Re: [hpe-dev-incubator/hpe-dev-portal] Create Blog “redfish-interoperability-profiles” (PR #2607)


@donzef commented on this pull request.

________________________________

In content/blog/redfish-interoperability-profiles.md<https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/2607#discussion_r1676114976>:

> +
+Requiring the implementation of only a small number properties *provide\[s] significant flexibility, and allow conforming implementations on a wide variety of products* as mentioned in the abstract of the <a href="https://www.dmtf.org/sites/default/files/standards/documents/DSP0272_1.8.0.pdf" target="_blank">standard document</a>
+
+### Who cares?
+
+Flexibility is great, but too much flexibility can become an issue for standard organizations, software projects or end users willing to move away from the Intelligent Platform Management Interface (<a href="https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-home.html" target="_blank">IPMI</a>) to Redfish for hardware management.
+
+Concerning standard organizations and software projects, the <a href="https://www.opencompute.org/about" target="_blank">Open Compute Project®</a> (OCP) and the <a href="https://wiki.openstack.org/wiki/Main_Page" target="_blank">OpenStack</a> projects can only adopt Redfish as their preferred management protocol if they can easily define some sort of "baseline" containing which property must, should or could be implemented in their managed nodes.
+
+Concerning OCP, the charter of the <a href="https://www.opencompute.org/projects/hardware-management" target="_blank">Hardware Management Project</a> mentions: "*The hardware management specification incorporates \[...] tools and best practices \[...] for remote machine management*". This means that any server compliant to this specification must implement the network protocol(s) mentioned in the baseline.
+
+Systems supported by the OpenStack <a href="https://wiki.openstack.org/wiki/Ironic" target="_blank">Ironic</a> (bare metal machine provisioning) and the <a href="https://wiki.openstack.org/wiki/Valence" target="_blank">Valence</a> projects (system lifecycle management) must implement as well a baseline of features containing at least the possibility to be powered on and off remotely.
+
+Redfish clients designed for managing multi-vendor systems have also a need for a list of mandatory and recommended features. For example, if a system cannot return its BMC's firmware version, the client will have difficulties to perform firmware updates.
+
+## Redfish Interoperability Profiles


For now, I'll remove leading upper cases and ask for confirmation.

—
Reply to this email directly, view it on GitHub<https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/2607#discussion_r1676114976>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASPH7ROLERXSDJ47Z7WPYU3ZL7ZXDAVCNFSM6AAAAABKJKREZ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZVGIYDINRQHE>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-07-22 15:24 UTC, merged