Create Blog “greenlake-api-how-to-generate-aceess-token-in-python”
hpe-dev-incubator/hpe-dev-portal pull request #2642
Opened 2024-07-26 03:56 UTC by buzzsubash

Automatically generated by Netlify CMS

2024-07-26 12:13 UTC, choukden requested changes
Hi Subash

Thank you very much for your contribution to the HPE Developer Community.

Please find here some comments and suggestions for you to consider and incorporate in the blog post. Once you have incorporated the suggestions (see tips below), I will engage with the HPE GreenLake Doc Writer team for the Editorial/Grammatical review before publishing the post to the HPE Developer Community portal.

I will also need to get your company's e-mail address in order for me to communicate with you via e-mail. 
My email address is denis.choukroun@hpe.com

Some tips to review the suggestions and acknowledge them in GitHub:

- Navigate to **_File Changed_** area to visualize the comments from start to the end, or navigate to **_Conversation_** area to visualize the comments per reviewer.

- You can mark the suggestion you have incorporated in your platform page entry in the CMS Workflow Editor by clicking on button **Resolve Conversation.**

Note we recommend you continue doing edits of your platform entry in the CMS Workflow editor while the entry is in the "**_In Review_**" column. Moving it back to the "**_Drafts_**" column would delete the Pull Request in GitHub.

Thanks!

Denis

2024-07-30 02:03 UTC, buzzsubash commented
Hi, I have update the article and made changes as advised.

2024-08-09 15:47 UTC, joe-boyle24 requested changes

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +## Use cases of fetching audit logs
```suggestion
## Use cases for fetching audit logs
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +### Step 1: Set up oauth2 authentication
```suggestion
### Step 1: Set up OAuth2 authentication
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +1. **Store Your Credentials**: Keep your client ID and secret safe but accessible to your script. A good practice is to store them in a text file. (In this case, I did save the client_Id in first lin
```suggestion
1. **Store Your Credentials**: Keep your client ID and secret safe but accessible to your script. A good practice is to store them in a text file. In this case, I did save the client_Id in first line and client_secret in second line.
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +Now that you have a token, you can ask HPE GreenLake for the logs.
```suggestion
Now that you have a token, you can fetch the logs from HPE GreenLake.
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +After getting the logs, you'll want to turn them into a format that’s easy to read and use.
```suggestion
After getting the logs, you'll want to convert them into a format that’s easy to read and use.
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +## How does it look like in excel?
```suggestion
## What does it look like in excel?
```

2024-08-09 15:47 UTC, joe-boyle24 commented on content/blog/greenlake-api-how-to-generate-aceess-token-in-python.md
> +I have used excel in this script just for testing and can be used with any of the databases including sqlite, postgres and oracle, and yes, python can do it, however, it varies on different use case,
```suggestion
I have used excel in this script just for testing and can be used with any of the databases including sqlite, postgres and oracle. Python can also do it, but the results vary depending on the use case, especially when it comes to real-time data monitoring or handling very large volumes of logs.
```

2024-08-14 10:14 UTC, buzzsubash commented
@joe-boyle24 Thank you, updated all suggestions

2024-08-14 11:21 UTC, merged