Create Blog “similar-document-search-using-apache-spark-with-tf-idf”
hpe-dev-incubator/hpe-dev-portal pull request #556
Opened 2021-06-22 14:23 UTC by burchems

Automatically generated by Netlify CMS

2021-06-22 18:33 UTC, choukden requested changes
Hi Nathan,

A few comments/request for changes to fix the issue you reported for the code snippet going beyond the normal bounds (specifying a language syntax for the code snippets should help fix the problem). Also, the em-dash syntax is not recognized by our CMS editor. I suggest another solution. And finally, I suggest we organize a short call (ideally after DIscover: this Friday or next week at your convenience) to work together to figure out why the image is not loaded.

Dale will go through the editorial review in the coming days.

Thanks
Denis

2021-06-22 18:33 UTC, choukden commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +```
Make sure you specify a language syntax for each and every code block snippet.
You can do it easily either from "Rich Text" mode (there is a "settings" wheel icon on the right side of the code block, or use "markdown" mode in the editor, and specify a language syntax.

I recommend syntax language "markdown" for this code block.

2021-06-22 18:33 UTC, choukden commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +```
For all the scala code block snippets throughout the post, please specify the language syntax ```scala

2021-06-22 18:33 UTC, choukden commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +To accomplish that goal, we decided to apply machine learning to the process, so that there is an automated program able to find similarities between the current message and the historical data. The
Unfortunately the Em-dash markdown syntax "&mdash" is not correctly interpreted by the CMS editor. 
I recommend using either a standard "dash" character or do a copy/paste of the EM-dash character here: —

2021-06-22 18:33 UTC, choukden commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +![](/img/image2.png)
I am not sure why the image is not loaded correctly.
I propose to arrange a quick call to work together and this issue and try to figure out the reason.

2021-06-23 17:58 UTC, drensing requested changes

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +To accomplish that goal, we decided to apply machine learning to the process, so that there is an automated program able to find similarities between the current message and the historical data. The
Should "finding similar documents." actually be "looking for similar documents."?

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +## Application 1 - Creates Features and Trains Model
Should "Creates Features..." actually be "Create Features..."?

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +2. Creates hashingTF, using HashingTF class available in Spark, and sets fixed-length feature vectors of 1000. It applies the hashing transformation to the document, resulting in the featurizedData.
Should "vectors of 1000." actually be "vectors to 1000."?

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +7. To save features vector to the MapR Database table, we have to convert the features vector to JSON format; for this, we create and register a UDF.
Recommend changing the semi colon to a period and starting the next sentence with "For this, we create..."

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +2. Loads in memory and caches the data with the features, saved previously.
remove the comma between "features" and "saved previously."

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +3. Creates a DataFrame with current message.
Add "the" prior to "current"

2021-06-23 17:58 UTC, drensing commented on content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
> +4. Then it finds the crossjoin DataFrame between the one element and all existing messages in the database and calculates the similarity.
Add comma after "Then" so it reads "Then, it finds the crossjoin..."

2021-07-13 05:15 UTC, closed without merging